services:
  db:
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'philhealth'
    ports:
      - 3309:3306
    expose:
      - 3306
    networks:
      - internalnet
    volumes:
      - db_data:/var/lib/mysql

networks:
  internalnet:
    driver: bridge

volumes:
  db_data: